import "./globals.css";

import { Roboto } from "next/font/google";
import { Header } from "../ui/Header";

const roboto = Roboto({
  subsets: ["latin"],
  weight: ["400", "500", "700"],
});

export const metadata = {
  title: "Booked - Home",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${roboto.className} antialiased bg-slate-50`}>
        <Header />

        <main className="space-y-40 h-screen">
          {children}
          <footer className='bg-[#5FA777] h-80' />
        </main>

      </body>
    </html>
  );
}
