name: Vercel Deploy FrontEnd

env:
  BRANCH_NAME: ${{ github.ref_name }}

on:
  push: 
    branches: 
      - develop
    paths:
      - "apps/web/**"
      - ".github/workflows/deploy_frontend.yml"

jobs:
  deploy_production:
    runs-on: ubuntu-latest
    steps:
      - name: Repository Checkout
        uses: actions/checkout@v3
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with: 
          node-version: 20

      - name: Install npm dependencies
        run: npm install

      - name: Build Next.js Project
        run: npm run web:build

      - name: Deploy to Vercel
        run: |
          npm install -g vercel
          vercel deploy --prod --token ${{ secrets.VERCEL_TOKEN }} --cwd apps/web
