name: Vercel Deploy FrontEnd

env:
  HUSKY: 'disable'
  BRANCH_NAME: ${{ github.ref_name }}
  VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID_FRONTEND }}
  VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID_FRONTEND }}

on:
  push: 
    branches: 
      - develop
    paths:
      - "apps/web/**"
      - ".github/workflows/deploy_frontend.yml"

jobs:
  deploy_production:
    runs-on: ubuntu-latest
    steps:
      - name: Repository Checkout
        uses: actions/checkout@v3

      - name: Install Vercel CLI
        run: npm install --global vercel@latest
      
      - name: Install npm dependencies
        run: npm install
        # run: |
        #   cd apps/web
        #   npm install

      - name: Build NextJS Project
        run: |
          cd apps/web
          npm run build

      - name: Pull Vercel Environment Information
        run: |
          cd apps/web
          vercel pull --yes --environment=production --token=${{ secrets.VERCEL_TOKEN }}
        
      - name: Build Project Artifacts
        run: |
          cd apps/web
          vercel build --prod --token=${{ secrets.VERCEL_TOKEN }}
        
      - name: Deploy Project Artifacts to Vercel
        run: |
          cd apps/web
          vercel deploy --prebuilt --prod --token=${{ secrets.VERCEL_TOKEN }}