name: Vercel Deploy FrontEnd

env:
  BRANCH_NAME: ${{ github.ref_name }}
  VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID_FRONTEND }}
  VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID_FRONTEND }}

on:
  push: 
    branches: 
      - develop
    paths:
      - "apps/web/**"
      - ".github/workflows/deploy_frontend.yml"

jobs:
  deploy_production:
    runs-on: ubuntu-latest
    steps:
      - name: Repository Checkout
        uses: actions/checkout@v3

      - name: Install Vercel CLI
        run: npm install --global vercel@latest

      - name: Install npm dependencies
        run: npm i

      - name: Build NextJS Project
        run: npm run web:build

      - name: Pull Vercel Environment Information
        run: vercel pull --yes --environment=production --token=${{ secrets.VERCEL_TOKEN }}
        
      - name: Build Project Artifacts
        run: vercel build --prod --token=${{ secrets.VERCEL_TOKEN }}
        
      - name: Deploy Project Artifacts to Vercel
        run: vercel deploy --prebuilt --prod --token=${{ secrets.VERCEL_TOKEN }}
      
      # - name: Setup Node.js
      #   uses: actions/setup-node@v4
      #   with: 
      #     node-version: 20

      # - name: Install npm dependencies
      #   run: npm install

      # - name: Build Next.js Project
      #   run: npm run web:build

      # - name: Deploy to Vercel
      #   run: |
      #     npm install -g vercel
      #     vercel deploy --prod --token ${{ secrets.VERCEL_TOKEN }} --cwd apps/web


